### ISSUE TITLE
Device Not Supported

### ISSUE THREAD

**Issue by ayo10** [xuanxuan000/linknlink-local#1]
Followed the instructions at https://drive.google.com/file/d/1ZCtu3rviCAtireOT1E2ooCOeSVK-Bidu/view and got "Device not supported" when I got to the add integration part. Yes, the IP is correct. 

Although, I did the modbus style installation previously, but removed it after the first failed attempt. 

```
2024-03-07 11:00:41.872 ERROR (MainThread) [custom_components.linknlink.config_flow] Unsupported device: 0xac7b. If it worked before, please open an issue at https://github.com/home-assistant/core/issues
```

**Comment by uzi2git2** [comment]
Same issue here...

**Comment by xuanxuan000** [comment]
I have fixed it. Please try again.

**Comment by ayo10** [comment]
Had to reload the integration in HACS, but it works now. But, now am getting no motion.

**Comment by gracar2002** [comment]
Also getting this issue (downloaded at 23:47 UTC 9-Mar). Hadn't had any Mobus integration:

`This error originated from a custom integration.

Logger: custom_components.linknlink.config_flow
Source: custom_components/linknlink/config_flow.py:39
integration: LinknLink (documentation)
First occurred: 8 March 2024 at 23:54:22 (4 occurrences)
Last logged: 20:07:28

Unsupported device: 0xac99`

**Comment by xuanxuan000** [comment]
The motion function of the ehub has been repaired.

**Comment by xuanxuan000** [comment]
> Also getting this issue (downloaded at 23:47 UTC 8-Mar). Hadn't had any Mobus integration:
> 
> `This error originated from a custom integration.
> 
> Logger: custom_components.linknlink.config_flow Source: custom_components/linknlink/config_flow.py:39 integration: LinknLink (documentation) First occurred: 8 March 2024 at 23:54:22 (4 occurrences) Last logged: 20:07:28
> 
> Unsupported device: 0xac99`

'0xac99' is not in the supported list. We only support LinknLink devices, such as eHub eTHS and eMotion.

**Comment by Puntoboy** [comment]
Any news when the eHub will be supported please?

**Comment by Puntoboy** [comment]
> > Any news when the eHub will be supported please?
> 
> Almost there, just a bit more.

Any news?

**Comment by jonathh21** [comment]
Dead keen here!

**Comment by xuanxuan000** [comment]
I've upgraded it. Please update and try again.
Given that I am using the latest version of the hardware development, there may be problems with older devices.
If you have any questions, please contact me.
