### ISSUE TITLE
Not seeing eHub motion

### ISSUE THREAD

**Issue by wifispray** [xuanxuan000/linknlink-local#2]
Not seeing motion working on eHub

Firmware: 62107
MAC: E0:4B:41:00:8C:13

<img width="1061" alt="image" src="https://github.com/xuanxuan000/linknlink-local/assets/28165635/b1c3286a-a5b8-43ba-a0c7-564fc5818fa7">

**Comment by ayo10** [comment]
Me too.

**Comment by xuanxuan000** [comment]
I have fixed it. Please try again.
