### ISSUE TITLE
Is the eRemote planned to be supported?

### ISSUE THREAD

**Issue by wifispray** [xuanxuan000/linknlink-local#3]
<img width="426" alt="image" src="https://github.com/xuanxuan000/linknlink-local/assets/28165635/70c263cf-cd80-4843-9950-b8e373a7659e">

**Comment by xuanxuan000** [comment]
> <img alt="image" width="426" src="https://private-user-images.githubusercontent.com/28165635/312147065-70c263cf-cd80-4843-9950-b8e373a7659e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTMwNDgsIm5iZiI6MTcxMDI5Mjc0OCwicGF0aCI6Ii8yODE2NTYzNS8zMTIxNDcwNjUtNzBjMjYzY2YtY2Q4MC00ODQzLTk5NTAtYjhlMzczYTc2NTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAxMTkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZjRlY2U0MGNiNDk1OTY0ZThkYzM5MmVlZGUxZDlmYmRlMWVmM2ZhYWY0YTY5YTkzYjZhZTI2MjZiYWI5NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pGfksuDxNKNOUhTwikF9VkBn4qwlRy8Ghx_byrEoJ_o">

Yes, it is in progress.

**Comment by wifispray** [comment]
any idea on when it will be released?

**Comment by Puntoboy** [comment]
Waiting as well. Thanks.

**Comment by jonathh21** [comment]
I think this is what I am after too, just followed a video but get device not supported.

**Comment by Delfairen** [comment]
Also hear for more info on the eRemote

**Comment by xuanxuan000** [comment]
Hey everyone, you can now add eRemote. It supports infrared remote control and learning. When the new firmware version is updated, I will simultaneously update the function to add sub-devices.

**Comment by Puntoboy** [comment]
> Hey everyone, you can now add eRemote. It supports infrared remote control and learning. When the new firmware version is updated, I will simultaneously update the function to add sub-devices.

How do I use it for infrared only without the firmware update?

**Comment by xuanxuan000** [comment]
> > Hey everyone, you can now add eRemote. It supports infrared remote control and learning. When the new firmware version is updated, I will simultaneously update the function to add sub-devices.
> 
> How do I use it for infrared only without the firmware update?

I'm writing the instructions. Please wait a moment.

**Comment by Puntoboy** [comment]
Oh, does that work if I get the device setup failed message without the firmware update?

**Comment by rijk82** [comment]
Thanks for the documentation – all seems ok up to step 2 but then I get the below error - failed setup [errno -5] the device storage is full – any ideas?
![image](https://github.com/xuanxuan000/linknlink-local/assets/19733272/18754760-9c1f-4655-862b-df5a384db943)

**Comment by Puntoboy** [comment]
Same error I got.

**Comment by jonathh21** [comment]
Same.

Also worth noting that the integration showed NO update on HACS.

Because I am impatient I redownload it to even get this far...

**Comment by Puntoboy** [comment]
There was an update for mine, but it had been a week or so since I last checked.

**Comment by xuanxuan000** [comment]
I used the old firmware version for testing and fixed the bug.
Please try again.

**Comment by Puntoboy** [comment]
> > > Hey everyone, you can now add eRemote. It supports infrared remote control and learning. When the new firmware version is updated, I will simultaneously update the function to add sub-devices.
> > 
> > 
> > How do I use it for infrared only without the firmware update?
> 
> https://drive.google.com/file/d/1jUhdi4ZfFOZ5k7JIs1E8WBczF3m5uQp4/view?usp=sharing

I've tried this guide, which is essentially the same as the Broadlink version, and I can't get it to work. It seems to learn the command but won't send it. 

If I use the app on my phone I can see the LED light up when I send a command, however when I use HA to send the command, the LED doesn't light up. 

My YAML send command

`service: remote.send_command
target:
  entity_id:
    - remote.linknlink_eremote
data:
  num_repeats: 1
  delay_secs: 0.4
  hold_secs: 0
  command: power
  device: tv`


My YAML learn command:

`service: remote.learn_command
data:
  command_type: ir
  device: tv
  command: power
target:
  entity_id: remote.linknlink_eremote`


I can see the remote command stored in HA

`{
  "version": 1,
  "minor_version": 1,
  "key": "linknlink_remote_e04b41009997_flags",
  "data": {}
}`

**Comment by rijk82** [comment]
Same. The learning reports as successful but no IR code is actually stored in the .storage/linknlink_remote_e04XXXX_codes file (i.e. Input below is blank):

```
{  "version": 1,  "minor_version": 1,  "key": "linknlink_remote_e04XXXX_codes",   "data": {    "Audio": {      "Input": ""    }  } }
```

**Comment by Puntoboy** [comment]
Yep, if I look at one of my Broadlink commands, there's a code in there with it.

`{
  "version": 1,
  "minor_version": 1,
  "key": "broadlink_remote_24dfa734c16c_codes",
  "data": {
    "projector": {
      "Power": "JgBYAAABJpAUEhMSFBEUNhQRFBEUEhMSFBEUNhQ1FBIUNRQSFBEUEhM2FDYUNRQSExIUERQSEzYUEhMSFBEUNhQ1FDYUNRQSFAAFfgABJkgUAAwYAAElSRQADQU="
    }
  }
}`

**Comment by xuanxuan000** [comment]
The data format of the hardware reply has changed, I have fixed it.
Please update and try again.

**Comment by Puntoboy** [comment]
> The data format of the hardware reply has changed, I have fixed it.
> 
> Please update and try again.

Is there an updated plugin? I can't see it in my install. I have version 8f33446.

**Comment by xuanxuan000** [comment]
> > The data format of the hardware reply has changed, I have fixed it.
> > Please update and try again.
> 
> Is there an updated plugin? I can't see it in my install. I have version [8f33446](https://github.com/xuanxuan000/linknlink-local/commit/8f33446241f88e4a33576861cc060ed6f1b4c868).

The latest commit is c398379.

**Comment by Puntoboy** [comment]
It's just appeared. Than you.

**Comment by rijk82** [comment]
All working for me now, thank you

**Comment by Puntoboy** [comment]
Yep, all working here now as well, thank you :)
