### ISSUE TITLE
Works only occasionally 

### ISSUE THREAD

**Issue by RobertBasil** [xuanxuan000/linknlink-local#4]
While my LinkNLink app reports my presence or lack of presence every time within 1 second. The HA integration only sees it once out of every 5-6 times and even with it does it take up to 10 seconds to register.

**Comment by xuanxuan000** [comment]
> While my LinkNLink app reports my presence or lack of presence every time within 1 second. The HA integration only sees it once out of every 5-6 times and even with it does it take up to 10 seconds to register.

The current approach is to check the status through polling. It will be updated to message push in the future.
