### ISSUE TITLE
Device Storage Full - eRemote

### ISSUE THREAD

**Issue by Puntoboy** [xuanxuan000/linknlink-local#5]
I downloaded the latest update today and getting Device Storage full when adding my eRemote

```
This error originated from a custom integration.

Logger: custom_components.linknlink.coordinator
Source: helpers/update_coordinator.py:315
integration: LinknLink (documentation)
First occurred: 23:38:11 (21 occurrences)
Last logged: 23:58:25

Unexpected error fetching linknlink-e04b41009997 data: [Errno -5] The device storage is full
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linknlink/coordinator.py", line 137, in _async_update_data
    data = await self.async_request(self.api.check_sensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linknlink/coordinator.py", line 128, in async_request
    return await self.hass.async_add_executor_job(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 198, in check_sensors
    pid_to_did_map = self.getalldev()
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 170, in getalldev
    resp = self._sendV2(0x0b0e, """{"count":16,"index":0,}""".encode('utf-8')) # max 16dev
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 109, in _sendV2
    e.check_error(resp[0x22:0x24])
  File "/usr/local/lib/python3.12/site-packages/linknlink/exceptions.py", line 152, in check_error
    raise exception(error_code)
linknlink.exceptions.StorageError: [Errno -5] The device storage is full

```

**Comment by xuanxuan000** [comment]
> I downloaded the latest update today and getting Device Storage full when adding my eRemote
> 
> ```
> This error originated from a custom integration.
> 
> Logger: custom_components.linknlink.coordinator
> Source: helpers/update_coordinator.py:315
> integration: LinknLink (documentation)
> First occurred: 23:38:11 (21 occurrences)
> Last logged: 23:58:25
> 
> Unexpected error fetching linknlink-e04b41009997 data: [Errno -5] The device storage is full
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/linknlink/coordinator.py", line 137, in _async_update_data
>     data = await self.async_request(self.api.check_sensors)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/linknlink/coordinator.py", line 128, in async_request
>     return await self.hass.async_add_executor_job(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 198, in check_sensors
>     pid_to_did_map = self.getalldev()
>                      ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 170, in getalldev
>     resp = self._sendV2(0x0b0e, """{"count":16,"index":0,}""".encode('utf-8')) # max 16dev
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 109, in _sendV2
>     e.check_error(resp[0x22:0x24])
>   File "/usr/local/lib/python3.12/site-packages/linknlink/exceptions.py", line 152, in check_error
>     raise exception(error_code)
> linknlink.exceptions.StorageError: [Errno -5] The device storage is full
> ```

I have fixed it. Please try again.
Given that I am using the latest version of the hardware development, there may be problems with older devices.

**Comment by Puntoboy** [comment]
I bought my eRemote only a month or so ago.

I have updated the plugin, rebooted Home Assistant and unfortunately I get the same error.

`This error originated from a custom integration.

Logger: custom_components.linknlink.coordinator
Source: helpers/update_coordinator.py:315
integration: LinknLink (documentation)
First occurred: 09:57:25 (5 occurrences)
Last logged: 09:58:05

Unexpected error fetching linknlink-e04b41009997 data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linknlink/coordinator.py", line 137, in _async_update_data
    data = await self.async_request(self.api.check_sensors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/linknlink/coordinator.py", line 128, in async_request
    return await self.hass.async_add_executor_job(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 198, in check_sensors
    pid_to_did_map = self.getalldev()
                     ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 170, in getalldev
    resp = self._sendV2(0x0b0e, """{"count":16,"index":0,}""".encode('utf-8')) # max 16dev
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 115, in _sendV2
    e.check_error(resp[0x22:0x24])
  File "/usr/local/lib/python3.12/site-packages/linknlink/exceptions.py", line 152, in check_error
    raise exception(error_code)
linknlink.exceptions.StorageError: [Errno -5] The device storage is full`

**Comment by xuanxuan000** [comment]
> I bought my eRemote only a month or so ago.
> 
> I have updated the plugin, rebooted Home Assistant and unfortunately I get the same error.
> 
> `This error originated from a custom integration.
> 
> Logger: custom_components.linknlink.coordinator Source: helpers/update_coordinator.py:315 integration: LinknLink (documentation) First occurred: 09:57:25 (5 occurrences) Last logged: 09:58:05
> 
> Unexpected error fetching linknlink-e04b41009997 data Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh self.data = await self._async_update_data() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/linknlink/coordinator.py", line 137, in _async_update_data data = await self.async_request(self.api.check_sensors) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/linknlink/coordinator.py", line 128, in async_request return await self.hass.async_add_executor_job(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 198, in check_sensors pid_to_did_map = self.getalldev() ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 170, in getalldev resp = self._sendV2(0x0b0e, """{"count":16,"index":0,}""".encode('utf-8')) # max 16dev ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/linknlink/remote.py", line 115, in _sendV2 e.check_error(resp[0x22:0x24]) File "/usr/local/lib/python3.12/site-packages/linknlink/exceptions.py", line 152, in check_error raise exception(error_code) linknlink.exceptions.StorageError: [Errno -5] The device storage is full`

The hardware needs to be upgraded. I am considering providing infrared function first, and I will upload other devices after you update the firmware.wait a moment.

**Comment by Puntoboy** [comment]
Infrared is what I need :) Thanks.

Do you have a URL for the firmware update please?

**Comment by xuanxuan000** [comment]
> Infrared is what I need :) Thanks.
> 
> Do you have a URL for the firmware update please?

It's still being tested. It's unstable. I'm not authorized to distribute it. Sorry.

**Comment by Puntoboy** [comment]
No worries. Please let me know when it's ready. Thank you

**Comment by Puntoboy** [comment]
Thanks to your last update, the "Device Storage Full" message is gone. I'm going to try and program the infrared controls.
