### ISSUE TITLE
BLE Remote Support

### ISSUE THREAD

**Issue by ASimpleTechie** [xuanxuan000/linknlink-local#6]
I have successfully added the eRemote (thank you for getting that device integrated). I was just wondering if the new BLE Remote that connects to the eRemote is or will be usable in Home Assistant at some point? I want to be able to press any of the buttons on the remote to trigger things within Home Assistant. Thank you again for your awesome work.

**Comment by xuanxuan000** [comment]
> I have successfully added the eRemote (thank you for getting that device integrated). I was just wondering if the new BLE Remote that connects to the eRemote is or will be usable in Home Assistant at some point? I want to be able to press any of the buttons on the remote to trigger things within Home Assistant. Thank you again for your awesome work.

I had added this feature in previous versions, but it requires hardware support. Currently, only devices from China can use the latest firmware. You can ask the manufacturer to update it as soon as possible. And then we can continue moving forward.

**Comment by ASimpleTechie** [comment]
Thank you for your prompt response. I will try get in touch with them.
